# link to all front matter variables
# https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-variables/

# supported latex functions
# https://katex.org/docs/supported.html

baseURL: https://www.everett-witt.com/
languageCode: en-us
title: everwitt7
paginate: 7
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

# TODO: add pages to Archive, etc... like they have in the example
languages:
    en:
        languageName: English
        weight: 1
        menu:
            main:
                - name: Archive
                  url: archives
                  weight: 5
                - name: Search
                  url: search/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 10
                - name: Categories
                  url: categories/
                  weight: 10

outputs:
    home:
        - HTML
        - RSS
        - JSON


params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: everwitt7
    description: making some thoughts public
    # author: Everett Witt
    # author: ["Me", "You"] # multiple authors
    # images: ["papermod-cover.png"]

    keywords: [blog]
    # DateFormat: “January 2, 2006”
    languageAltTitle: English

    ShowReadingTime: true
    ShowShareButtons: false
    ShowCodeCopyButtons: true
    ShowFullTextinRSS: false

    defaultTheme: light
    disableThemeToggle: true
    disableSpecial1stPost: true
    disableScrollToTop: true
    disableAnchoredHeadings: true

    hideMeta: false
    hideSummary: false
    showtoc: false
    tocopen: false

    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    comments: false


    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35


    profileMode:
        enabled: false
        title: PaperMod
        subtitle: PaperModSub
        imageUrl: resources/_gen/images/img.png
        imageTitle: my image
        imageWidth: 120
        imageHeight: 120
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags
            - name: Github
              url: "https://github.com/"
    
    
    homeInfoParams:
        # Title: "PaperMod"
        Content: >
            Welcome to Everett Witt's website
    
    socialIcons:
        - name: github
          url: "https://github.com/everwitt7"
        - name: twitter
          url: "https://twitter.com/home"
        # - name: KoFi
        #   url: "https://ko-fi.com/adityatelange"


    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    
    # TODO: THIS DOES NOT SEEM TO BE WORKING
    assets:
        favicon: "static/favicon.ico"
        favicon16x16: "static/favicon-16x16.png"
        favicon32x32: "static/favicon-32x32.png"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"


    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page


    # schema:
    #   publisherType: Organization
    #   sameAs: [url1, url2]


    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

    # editPost:
    #     URL: "https://github.com/<path_to_repo>/content"
    #     Text: "Suggest Changes" # edit text
    #     appendFilePath: true # to append file path to Edit link


taxonomies:
    category: categories
    tag: tags
    series: series

markup:
    goldmark:
        renderer:
            unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true


